### ISSUE TITLE
Condensed Mode: Minimum Height

### ISSUE THREAD

**Issue by jleandroperez** [Automattic/simplenote-ios#1045]
### Details:
Our Notes List should display cells that are, at least, 44pt height whenever condensed mode is enabled.

Ref.:

<img width="300" src="https://user-images.githubusercontent.com/1195260/100096302-9653fe80-2e3a-11eb-98be-3046349f7f9e.png">

**Comment by pachlava** [comment]
[texting] Verified the feature on iPhone XR | iOS 14.3 | SN 4.31
Did not measure the cells height, but they definitely are higher than in 4.30

**Comment by reginabally** [comment]
We received feedback in 3741782-zen regarding this change so I thought of sharing it here.

> The condensed view is not so condensed anymore. It’s annoying that I have to scroll more to reach all my notes and I have less of an overview now that less notes fit on my screen. The font size has not changed so the only thing different is that there is more unused pixels now, I don’t understand why that would be an improvement. Please provide the more condensed option back, as I thought it was really useful.

**Comment by SylvesterWilmott** [comment]
Thanks @reginabally 

The minimum tap target area according to the Apple Human Interface Guidelines is 44pt. This rule can be bent sometimes but in this case, tappable regions appear adjacent to other tappable regions. In order to keep the app accessible it was important to enforce the minimum tap target area here.
