### ISSUE TITLE
Crashes while generating excerpts for ja, zh, ko locales

### ISSUE THREAD

**Issue by eshurakov** [Automattic/simplenote-ios#1055]
There is an issue on Sentry, but unfortunately couldn't reproduce it myself. So far it happens for users whose device locale is set to `ja`, `zh` or `ko`.

[SIMPLENOTE-IOS-9RV](https://sentry.io/share/issue/5dc9b7f0df0047e1bc69469b2e35847d/)

**Comment by rezzap** [comment]
We have a user who has reported the following characters in search cause a crash:

> There are three types of characters mixed in my notes, English, Italian, Japanese.
I am trying to search the notes using English and Italian characters then the app crashes.
I cannot type more than two characters because it crashes immediately when I type only one character.

>Regarding the app crash, the characters that crash are followings.
* Almost every small alphabet from "a" to "z" except "x"
* Special small alphabets ; "à", "ì", "è", "é", etc.
* Almost every big alphabet from "A" to "Z" except "X"
* Almost every numbers from "0" to "1" except "5"

### Device Info:

iPhone11
iOS 13.5.1
simplenotes for iOS ver. 4.29

iPhone7
iOS14.1
simplenotes for iOS ver. 4.29

From 3567743-zen
