### ISSUE TITLE
Markdown H5 is automatically converted into upper case

### ISSUE THREAD

**Issue by iamgabrielma** [Automattic/simplenote-ios#1304]
Reported on 4010099-zen 

When using markdown, H5 defaults to uppercase no matter the case that is used:

### Expected
That H5 works as other headings, using upper or lowercase when required.

### Reproduced
- 1 Open a note or edit an existing one
- 2 Write `##### my h5 heading` in the editor
- 3 Switch to markdown preview
- 4 See `MY H5 HEADING`

<img width="332" alt="Screenshot 2021-06-02 at 16 42 30" src="https://user-images.githubusercontent.com/3812076/120458941-e7ccdf80-c3c1-11eb-8a7d-5aacddcebc29.png">

Apple | iPhone | iOS 14.2 | Simplenote 4.35

**Comment by charliescheer** [comment]
I took a look and in the CSS file for the markdown preview, H5s are set to uppercase and none of the other headings are

https://github.com/Automattic/simplenote-ios/blob/704d77138b4ad5738bf2ef3620ad3ee7a81f013a/Simplenote/Resources/markdown-default.css#L74-L81

@SylvesterWilmott is this intentional?  Should H5s in markdown preview be uppercase?

I checked out a few other version of SN to mixed results.
MacOS - Capitalizes H5
Electron and Web - Don't process ## to headings

**Comment by SylvesterWilmott** [comment]
This is quite a typical way to handle instances where a header may be indistinguishable from bold paragraph text. However, I agree with the issue that it's frustrating to have h5 and h6 forced uppercase. I think we can simply remove the `text-transform: uppercase` line.

**Comment by charliescheer** [comment]
Thanks @SylvesterWilmott I want to do a little bit of rearranging how the CSS is loaded into iOS, and will also make the same changes on MacOS
