### ISSUE TITLE
More enhancements to notes multi-selection

### ISSUE THREAD

**Issue by pachlava** [Automattic/simplenote-ios#1308]
### What

After more comparison with similar behaviour in Messages, it feels like doing this will improve the experience:

1. Delete button should be disabled when no note is selected
2. 'Edit' button should be disabled when there are no notes in notes list
3. Search bar should be disabled when in Edit mode (tapping the search bar accidentally will end the edit mode)

Debatable, but:

4. Additional highlighting of selected note cell looks redundant

### Why
Improved usability

cc @SylvesterWilmott

**Comment by charliescheer** [comment]
>Delete button should be disabled when no note is selected

Great suggestion! Fixed this one.

>'Edit' button should be disabled when there are no notes in notes list

Moving the edit mode into the context menu should fix this one as the only way to access the edit mode would require long pressing on an existing note

>Search bar should be disabled when in Edit mode (tapping the search bar accidentally will end the edit mode)

I had set this up so that the search mode would cancel edit mode.  For me I found it more convenient to exit the edit mode if the search was tapped on.  But that being said I can also see how disabling the search is a good option.  I checked the Apple notes app and when in edit for that app the search is disabled.  @SylvesterWilmott  WDYT should search be disabled when in edit mode?

**Comment by SylvesterWilmott** [comment]
>WDYT should search be disabled when in edit mode?

I don't feel too strongly about it. I would say let's follow what Apple does and disable the search so we have behaviour that's consistent with the system. Disabling search also seems to be the case in Pages, Mail, Numbers, Keynote etc.

**Comment by pachlava** [comment]
This issue can be closed since everything mentioned here was fixed in #1328
