### ISSUE TITLE
Brackets Added When Sharing Links from A Mobile Browser

### ISSUE THREAD

**Issue by erricgunawan** [Automattic/simplenote-ios#1477]
When sharing a link from a web browser (i.e. Chrome), brackets were added enclosing the link.

### Expected

It should add the link as is, i.e.:

```
https://simplenote.com
```

### Observed

Brackets were added enclosing the link, so it becomes:

```
[https://simplenote.com]
```

### Reproduced

1. Open a mobile browser (i.e. Chrome) and open a page/link.
2. Tap on the share button in the address bar
3. Choose Simplenote
4. Bracket was added on the link

### Additional Info

I tried on the Simplenote Android, and the bracket was not added.

In addition, the page title becomes the Note's title, and the link becomes the Note's content.

In iOS, the link (with the bracket) becomes the Note Title.

Reported on: 4574645-zen with a video recording (not posted here since it might contain personal info).

Refr: p1639534809096300-slack-C03P63CP9

Make|Model|iOS Version|App Version | Browser Version
-|-|-|-|-
iPhone | iPhone 7 | iOS 15.1 | Simplenote iOS 4.47 | Chrome 96.0.4664.94

**Comment by ChrissiePollock** [comment]
The customer responded with the following information: Latest of everything. iPhone 12. Latest beta. Latest simple note and latest chrome versions

**Comment by charliescheer** [comment]
The brackets are markdown for links.  When the link is being shared Simplenote iOS is automatically identifying the link and applying markdown to it.  This is what I would expect sharing a link.  Adding or not adding the brackets is gonna be a matter of opinion on a per user basis if they use markdown or not.  I am gonna close this as it is intentional.  Feel free to reopen if we start seeing more requests
