### ISSUE TITLE
Manual Sync Button

### ISSUE THREAD

**Issue by aamills** [Automattic/simplenote-ios#151]
From a couple users: 

#2763127-t
It`s a great app, but I beg of you, please add sync button to this app! I use simplenote on my android device and PC, and it is very, very ridiculous to wait, while it will auto-sync my notes, when I connect my devices to wi-fi. You have a great app, Thank you! But please! Add sync button! 

#2785856-t
I am more an old school guy and I would prefer "sync button" to make an app sync if it does not do it automatically.

#3309826-t
Could you please make something like "push to cloud" button?

**Comment by jleandroperez** [comment]
Closing this one since this will not gonna happen, ever. Simplenote is based on the Simperium framework. Long story short:

- Changes are automatically tracked
- Whenever our backend becomes available, they will be pushed

The protocol is designed to retry on failure, and is constantly trying to reach our endpoint. There is absolutely no need for a *Sync Button*, since there is... literally, nowhere to hook it / no need for it.

Thanks @aamills!!
