### ISSUE TITLE
UI tests can't run on CI

### ISSUE THREAD

**Issue by crazytonyli** [Automattic/simplenote-ios#1536]
The UI tests CI step is failing because [fastlane fails to find the test accounts](https://github.com/Automattic/simplenote-ios/blob/8d061a19283ea8d113203a5b80c92e7c8753a214/fastlane/Fastfile#L1064) which are stored in kvdb.io.

**Comment by pachlava** [comment]
@crazytonyli 👋 

The free variant of buckets on kvdb.io lasts for 3 months IINM. To restore the bucket, it's enough to run one command from terminal: p1667903243007039/1658172902.518279-slack-C02H2SVA1L5

I just did that, and the testing PR #1537 [started executing the tests](https://buildkite.com/automattic/simplenote-ios/builds/598#018b8f2b-5567-4f24-8bf3-4e7642418ef5/443-466). All of them failed, however 😆, which is a good sign, because most probably the reason is the same for all. I'll have a look at the reason later this week, but I think the current issue can be closed.

**P.S.** Given the repo activity level, I don't think it makes sense to pay for the bucket. When the repo was active, the selection of test accounts was really needed, to avoid race scenarios, because the tests hit the real API. Now, I think we can either stick to running this command every 3 months or even get back to using one test account. WDYT?

**Comment by crazytonyli** [comment]
@pachlava Thanks for looking into this issue.

Do you think we can put the `UI_TESTS_ACCOUNTS_JSON_URL` content into the pipeline's secret file? So that we don't need to go through kvdb.io?

**Comment by pachlava** [comment]
@crazytonyli, I think it's a matter of scope / visibility. This should be an environment variable which can be read/written by different builds simultaneously. AFAIK, this was hard to achieve when CircleCI was in use. Possibly with BK this is easier?

**Comment by charliescheer** [comment]
I brought this issue up recently cause we are cleaning up the SNiOS repo right now, and the CI failing got noticed.  @spencertransier got the CI running again.  Gonna close this
