### ISSUE TITLE
Dark Theme: Incorrect text color

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#16]
#### Report:

```
(...) weird bug where the dark theme showed dark text in the note editor. Instead of the light blue color.
then changed the cursor location, and it all magically turned the correct color.
```

Let's review the code in charge of setting the TextView's text color, and make sure there are no invalid flows there.

@dmsnell just managed to reproduce this with the following steps:

```
1. Log into Simplenote OSX and iOS
2. OSX in white mode + iOS in dark mode
3. In iOS, tap over a note to get to the details view (do NOT get the keyboard onscreen)
4. Edit the same note in OSX
5. Once the change is onscreen, tap anywhere

Result: Keyboard onscreen. (iOS’s text goes dark?)
```

I've been unable to trigger this on my side (Latest iOS build + Simplenote's AppStore build). Scheduling this bug for the next release!

@astralbodies "Since I'm working on #323 I'll pull this one too."

Opened by @jleandroperez

**Comment by KokkieH** [comment]
Had another report of what seems to be the same issue via [Twitter](https://twitter.com/user/status/825710480555651072) on the latest iOS version. However, this user is using iOS only, based on their description:

 In both iPad and iPhone app, editing a note in dark theme turns the text from light to dark so that it's hardly visible

![c3ohb4qwyaax_8n](https://cloud.githubusercontent.com/assets/11873759/22404843/f4f2ce7a-e641-11e6-8af7-621437fb7d5c.jpg)

**Comment by bummytime** [comment]
Closing in favor of #40
