### ISSUE TITLE
Pressing Return/Space after any emoji changes it into strange character

### ISSUE THREAD

**Issue by zdenys** [Automattic/simplenote-ios#221]
Keyboard returns and spaces after an emoji character cause strange emoji character replacement and line breaks. Happens for any amoji and only in Simplenote.

Has been occurring 1-3x weekly for ~3 months.

User's screen recording: http://cld.wthms.co/yqdt0p
Ticket: #1390464-zen

iOS 11.4.1 
Simplenote 4.6.4 
iPhone 7 
Using standard iOS keyboard 
Keyboard autocorrect is OFF

**Comment by bummytime** [comment]
Unable to repro on iOS 12.2.

**Comment by jleandroperez** [comment]
We've recently fixed a bad bug when dealing with Emojis, in which the unicode sequence might have been getting split in half (and thus, causing strange characters to appear).

This bug would definitely explain this behavior.

Ref. #525

Closing this one, since it's expected to be fixed in 4.14. Thank you all!
