### ISSUE TITLE
Increase Tag Text Size

### ISSUE THREAD

**Issue by kristenzuck** [Automattic/simplenote-ios#284]
A customer using iOS app is requesting we increase the text size of tags on the tag list and at the bottom of notes. They're reporting it is difficult to tap on the tags with their finger to view other notes with that tag because the text is too small.

**Comment by bummytime** [comment]
Verified on iOS 12.1. This is an accessibility issue as well since the text size does not increase even if the system text is embiggened:

![Simulator Screen Shot - iPhone Xs - 2019-05-13 at 17 12 40](https://user-images.githubusercontent.com/154014/57657864-5738c200-75a2-11e9-821d-2a2e9f654eee.png)

**Comment by charliescheer** [comment]
I did some testing on this issue and the tag sizes and the tag suggestion popover both respond to dynamic type now.

<img src="https://cdn-std.droplr.net/files/acc_593859/1V9r6H" />

Tested on iPhone 8 iOS 14.3
iPhone 12 sim iOS 14.4
iphone 8 sim iOS 12.2
iphone 12 sim iOS 13.7

Closing issue
