### ISSUE TITLE
Show share/publish icon in note list

### ISSUE THREAD

**Issue by bummytime** [Automattic/simplenote-ios#312]
The (old) web app had the published icon for any individual note:

<img width="728" alt="sharing_icon" src="https://user-images.githubusercontent.com/154014/58282571-c022f580-7d6b-11e9-90df-c9b0f0f335df.png">

iOS does not. Let's fix that. 

Ref: https://github.com/Automattic/simplenote-macos/issues/4

**Comment by jleandroperez** [comment]
@SylvesterWilmott question for you sir!

Potentially the reason why this is missing in iOS is because of lack of spacing. See screenshots below.

We can, whenever a note is shared, display the `shared` icon on the left (and **only** in that scenario, of course, move the text to the right).

This would be [the original asset](https://app.simplenote.com/img/shared.png).

Potential idea below. It's either doing something like that, or simply **always** having a left padding.

@SylvesterWilmott thoughts? (if we do go this road, I'll definitely need to bug you with an asset for this new icon, since the one used by the web is tiny (12x12px), and It's nowhere to be found in Gridicons.

Thanks in advance!

![Simulator Screen Shot - iPhone SE - 2019-05-28 at 14 32 21 copy](https://user-images.githubusercontent.com/1195260/58499389-6b5df100-8156-11e9-8286-11daf6b3f4d5.png)

**Comment by bummytime** [comment]
@SylvesterWilmott @jleandroperez for context, this is what the current electron app does: https://github.com/Automattic/simplenote-electron/issues/227#issuecomment-495379169

<img width="327" alt="Screen Shot 2019-05-23 at 3 46 56 PM" src="https://user-images.githubusercontent.com/154014/58285273-1004bb00-7d72-11e9-9778-fbc5476fc71a.png">

**Comment by jleandroperez** [comment]
**Exactly**!!! I realized i didn't mention we could just place the icon **on the right hand side** and that's it.

Thanks for pointing it out Matt! We'd still have a slight deviation with the Web, but i think... right hand side is the way to go!

**Comment by bummytime** [comment]
> Thanks for pointing it out Matt! We'd still have a slight deviation with the Web, but i think... right hand side is the way to go!

Actually, the [new](https://app.simplenote.com/new) (soon to be only) website is also on the right side:

<img width="356" alt="Screen Shot 2019-05-30 at 11 15 19 AM" src="https://user-images.githubusercontent.com/154014/58647112-733fa180-82cc-11e9-9a58-e86508f23b6c.png">

so we should be all good @jleandroperez 😄

**Comment by SylvesterWilmott** [comment]
Agree here, right-hand side works well.

@jleandroperez I'll prepare that asset for you

**Comment by jleandroperez** [comment]
Thank you sir!
