### ISSUE TITLE
Search by swipe

### ISSUE THREAD

**Issue by Shtalin** [Automattic/simplenote-ios#397]
### What
Swipe from bottom to down (out of display) triggers action like click to search area(keyboard shows and search input focused)

### Why
   1. It seems useful and simple(NOTE))))
   2. You needn’t aim to tiny searchbar(and maybe hide seachbar when it’s empty!)
  3. I made it in my android app , so it tested in real life

### How
Bottom is area about 20% of screen  height ... to avoid keyboard fires when user just scroll notes

**Comment by jleandroperez** [comment]
Hello @Shtalin,

Thank you for the suggestion! but since the Search Bar is at the top of the notes list, and always visible, I'm afraid swiping down to toggle the first responder would potentially be confusing.

Plus: swipe down to do so isn't iOS standard, and might be a bit confusing to other users.

Thank you for your interest in Simplenote!
