### ISSUE TITLE
When OS and Simplenote are both set to Dark theme, unreadable text/dark overlay shows

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#40]
**New info: This seems to happen if Simplenote and iOS are both set to Dark theme, AND if iOS is set to Dark and Simplenote is set to System Default.**

A user reports that then they edit a note with the dark theme enabled the text in the note switches from blue to black and becomes difficult to read. I can reproduce this with some of my own notes but not all of them. Here's an example:
![img_1967](https://cloud.githubusercontent.com/assets/7946521/8431827/f9cabefc-1f33-11e5-935f-01e2d6922f8d.PNG)

Another report here:
https://twitter.com/ChanceArthur/status/632102403572113408

ticketid=2370648

**Comment by SiobhyB** [comment]
I wasn't able to reproduce but it sounds like the reporter of this three star review is seeing the same problem:

> When you turn on the dark mode and click “create a new note”, the text cursor completely disappears from the page and leaves you unable to see what you’re writing. 
> 
> This is a significant bug, it makes the app unusable when dark mode is active. Reinstalling did not help.

**Comment by msilbers** [comment]
Two more reports of this issue with much more information! This seems to happen if Simplenote and iOS are both set to Dark theme, but does NOT happen if iOS is set to Dark and Simplenote is set to System Default.

The issue is that when opening a note, the text looks faded out, or like there's a dark overlay over the note

![simp_dark1](https://user-images.githubusercontent.com/31680407/65837872-75d9f400-e2ca-11e9-85fd-bb3c47ed1c9f.jpg)

Model|Android Version|App Version
-|-|-
iPad Pro 12.9 inch, 3rd generation | iOS 13.1.1 | Simplenote 4.10
Apple iPad Air 2 | iOS 13.1.1 | Simplenote 4.10.1
iPhone 6 | iOS 12.4.2 | Simplenote 4.10.1
iPhone7 | iOS 13  | Simplenote 4.10.1

**Comment by joeboydston** [comment]
Reported by the same user above, this is an iPhone 6 (iOS 12.4.2 without dark mode). Here's another screenshot that might help:

![fullsizeoutput_ab3](https://user-images.githubusercontent.com/22623115/65961456-d88ad700-e413-11e9-8193-967771d546f5.jpeg)

**Comment by msilbers** [comment]
Reported again by an iOS user:

(iPhone 6) running OS 12.4.1 on Simplenote version 4.10.1.

**Comment by aheckler** [comment]
I can reproduce with my iOS settings on Light and Simplenote on Dark. 

It seems to happen whenever I completely quit the app, then open it fresh. The first note I go into will be affected, but as soon as I back out to the Notes list and go into another note (or even re-open the same note), everything is fine from that point on.

**Comment by aheckler** [comment]
2393380-zen is the same thing.

**Comment by sarahfg** [comment]
2397278-zen has another repeat of this
