### ISSUE TITLE
Search: Search strings not highlighted in search results, or when selecting specific note from results

### ISSUE THREAD

**Issue by abbnmn** [Automattic/simplenote-ios#433]
### step

> 1. a article like this
昔看黄菊与君别，今听玄蝉我却回。
五夜飕飗枕前觉，一年颜状镜中来。
马思边草拳毛动，雕眄青云睡眼开。
天地肃清堪四望，为君扶病上高台。
看
看
看
看
> 2. search the keyword 看
> 3. tap in the article detail

### Expected
as ios12
show the result number
jump to the keyword which input
tap the 【next】 button ，jump to the next keyword
keyword highlight

My device is  iPhone 6s ios13.1 app version is 4.10

**Comment by KokkieH** [comment]
We've had two more reports via Twitter:

https://twitter.com/Ealdorwolf/status/1176961509387317248 (contains video of the issue)

https://twitter.com/chise_z3/status/1176017912793948162 (contains screen shot of the issue)

#### Description

It appears that when searching, notes matching the search string appear, but the search term is not highlighted.

Clicking through to a note in results it opens the note on the first line, rather than at the search term, and the search term is not highlighted. Additionally the app indicates there are zero results for the search term.

Both Twitter users also report the change happened after updating to iOS 13.

**Comment by abbnmn** [comment]
> We've had two more reports via Twitter:
> 
> https://twitter.com/Ealdorwolf/status/1176961509387317248 (contains video of the issue)
> 
> https://twitter.com/chise_z3/status/1176017912793948162 (contains screen shot of the issue)
> 
> #### Description
> It appears that when searching, notes matching the search string appear, but the search term is not highlighted.
> 
> Clicking through to a note in results it opens the note on the first line, rather than at the search term, and the search term is not highlighted. Additionally the app indicates there are zero results for the search term.
> 
> Both Twitter users also report the change happened after updating to iOS 13.

Thank you ^-^

**Comment by jleandroperez** [comment]
Fixed via #425 

Simplenote 4.10.1 is scheduled for release soon, thanks for reporting this issue!!

**Comment by KokkieH** [comment]
That was quick! Thanks, @jleandroperez!

**Comment by jleandroperez** [comment]
Thank **you** @KokkieH !!!
