### ISSUE TITLE
Passcode screen can be shown without keyboard

### ISSUE THREAD

**Issue by kwonye** [Automattic/simplenote-ios#6]
I've got another report of this. The user was editing a note and received a text message. They replied to the text message then used the option to "Return to Simplenote" in the top left of their screen. However they were presented with the Simplenote passcode screen but not keyboard.

2572058-t

Originally by @tomwitkin

**Comment by Mrlodgical** [comment]
I've got another one with the same issue & was able to replicate 3311967

**Comment by kriskorn** [comment]
Another report in #1172481-zen

When user minimizes the app then reopens it again it doesn’t show the keyboard for them to enter their passcode. They have to close the app and start again for everything to work correctly.

**Comment by pauljacobson** [comment]
We have another report of this in 1281123-zen

Here is a screenshot:

![](http://cld.wthms.co/gdos1R+)

Simplenote: 4.6.2
iOS: 11.4.1

**Comment by bummytime** [comment]
**Update 5/13/2019 →** I am unable to repro this problem on iOS 12.2, Simplenote: 4.6.2. Since this appears to be intermittent, I'll leave this issue open for now.

**Comment by charliescheer** [comment]
I tested this a bit today and could not repo.

I tested with:
iPhone 8, iOS 14.3, SN 4.29
iPad mini 5, iOS 14.4, SN 4.29

Simulator:
iPhone 7, iOS 14.3, SN 4.28
iPhone 12, iOS 14.3, SN 4.28

On each device I tired leaving Simplenote by clicking on an active notification, swiping down to expose the notification view, selecting a notification from the notification view, and then in each case returning to Simplenote using the return to Simplenote option in the top left and the app switcher.  I also tried a returning to the home screen, and using the app switcher to leave and return to Simplenote.  In all cases the keyboard was available at the pin lock screen.

I'm going to close this issue for now, please feel free to re open if the issue is still occurring, and please comment with details about the device, operating system, Simplenote version, and some steps for reproducing

**Comment by eshurakov** [comment]
We will also be shipping a new version of passcode screen in version 4.30 (https://github.com/Automattic/simplenote-ios/issues/761)
