### ISSUE TITLE
"tag:" prefix gets localized and is harder to type in some languages

### ISSUE THREAD

**Issue by codebykat** [Automattic/simplenote-ios#860]
This is an interesting one!

A user reports (#3261645-zen):

> I like the idea of tag search very much, like “tag:food” for example. The problem is that I use Swedish language setting on my iphone. That means that I’d have to type “etikett:food” instead. That makes the feature so much less useful because it takes much longer to type. Could you please make it so that the use of “tag” works in any language so that I could use “tag:food” on my phone?

I'm not sure what the best course of action would be for this, since we probably don't want to remove the localized tag name prefix. I wonder if we can support both the English "tag:" and whatever the localized word for "tag:" is?

cc @SylvesterWilmott

**Comment by jleandroperez** [comment]
This behavior is definitely on purpose. We can support `tag:` in english, plus localized versions, not a problem.

Sly, should we go ahead with this one?

Thank you both!!!

**Comment by SylvesterWilmott** [comment]
I see no issue with supporting English prefix in tandem with the localized version. Let's go for it.

**Comment by charliescheer** [comment]
I went to do a bit of testing on this just now, and now "tag:" works in any language (or at least the languages I tested, French, French (Canadian), Swedish)
however the translated version of tag didn't work (fr: étiquette, sv: etikett) 

I don't see any PRs connected to this issue, but something may have happened in the recent changes to search.  @jleandroperez should the localized word for tag still be working along side the english tag in search?

**Comment by jleandroperez** [comment]
@charliescheer that would be right! we'd need to add support for `tag:` in English (unlocalized), along with localized support.

**Comment by eshurakov** [comment]
This issue is more tricky than it looks.
1. What happened that only non-localized `tag:` works? Some time ago we created a `SimplenoteSearch` framework to share some code between iOS and macOS. We also moved `NSLocalizedString("tag:", ...)` macro to the framework [(link)](https://github.com/Automattic/SimplenoteSearch-Swift/blob/main/Sources/SimplenoteSearch/Extensions/NSString%2BSearch.swift). I believe release scripts don't look for localized strings in the frameworks, that's why it became not localized.
2. What is the solution here? I think there can be several. 
2.1. Support localization in frameworks. A framework would have it's own `Localizable.strings` file and will be localized separately from the app. This one is big as I believe our release tools don't support this.
2.2. Move `NSLocalizedString("tag:", ...)` macro to the app and inject localization to the framework.
2.3. ?
