### ISSUE TITLE
Duplicate Tag Created When Renaming Tags

### ISSUE THREAD

**Issue by cupcakedream** [Automattic/simplenote-ios#99]
When renaming a tag and then editing a note with the renamed tag, the renamed tag shows up as a duplicate at the bottom of the tags list. When selected in the left column, both tags show the same list of notes.
1. Rename A Tag in the left column by ctrl-clicking
2. Select A Note that is tagged with the newly renamed tag
3. Click on one of the tags or in the tag area of the note
4. The duplicate tag shows up at the bottom of the list

If you rename the duplicate tag, the tags will be renamed in the notes as expected. When you click on the tags area in one of these notes, the original tag gets renamed, and yet another tag with the old tag name gets added near the bottom of the tag list. At that point, you'll have 2 duplicate tags at the bottom of the list.
1. Rename the duplicate tag in the tags column by ctrl clicking
2. Select the original tag in the tags column
3. Click on one of the tags or in the tag area
4. The original tag is renamed, and the old tag shows near the bottom of the list

I've also noticed that the tag labels in the notes can be different from the tag labels in the tag column when the duplicate tags are showing up. I haven't been able to reproduce the issue consistently though.

![screen](https://cloud.githubusercontent.com/assets/1387911/19834140/724ab704-9e29-11e6-8b3e-c890f124daf7.png)

**Comment by cupcakedream** [comment]
So it actually creates a second tag at the bottom with the same notes, so it appears the tag is just added a 2nd time to the bottom of the list and references the same notes (notes only have the single tag)

<img width="149" alt="screen shot 2016-10-29 at 5 57 16 pm" src="https://cloud.githubusercontent.com/assets/1387911/19833019/2bd74e40-9e01-11e6-93c5-dcbbe1ee0e56.png">

**Comment by rachelsquirrel** [comment]
Also reported here https://github.com/Automattic/simplenote-macos/issues/70

**Comment by carladoria** [comment]
reported here: 3194884-t  too

**Comment by gubrist** [comment]
![simplenote-1 1 1-setup_12 12 2017](https://user-images.githubusercontent.com/22197180/33898933-292275b6-df6a-11e7-8e25-0bcc4af35bad.JPG)

Thanks :-)

What has to be done now to erase the duplicated tags?

**Comment by bummytime** [comment]
**Update 5/14/2019 →** Still an issue in Simplenote 4.7.0, iOS 12.2

**Comment by gubrist** [comment]
Update 15.05.2019 → Still an issue in Simplenote Android 1.7.0 or (and) Simplenote Electron 1.5.0.
I am not able to trace which one did cause the Duplicate Tag

**Comment by bummytime** [comment]
Ref: https://github.com/Automattic/simplenote-macos/issues/70

**Comment by designsimply** [comment]
I tried following the steps provided to see if I could get any duplicate tags to show up if I renamed a tag but no duplicates showed up in my test. ([2m36s](https://cloudup.com/cKTB_UtgnyC))

<sup>Tested with Simplenote iOS 4.27.0.0 (MS App Center beta) on iPhone 11 iOS 14.1.</sup>

Closing as I was unable to repro in testing with Simplenote iOS 4.27.0.0 and because [this comment](https://github.com/Automattic/simplenote-macos/issues/70#issuecomment-691106113) mentions past work to enhance Tag Validation and says duplication should not be an issue anymore.

Please comment to ask for this issue to be re-opened if you can still replicate the issue or if you see a problem in my testing video linked above. Thank you!

**Comment by jleandroperez** [comment]
Thank you Sheri!
